version: "3.7"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: taxidata
    volumes:
      - ./pgdata:/home/ubuntu
    ports:
      - '5432:5432'
  web:
    image: taxi-insights
    depends_on:
      - db
    ports:
    - "4000:4000"